##aadas#
---
- hosts: test
  become: true
  tasks:
    - name: Install Docker
      apt:
name: docker.io
        state: present
        update_cache: true
 
    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true
